In [ ]:
# Linear Algebra Notebook

This notebook covers the fundamental concepts of linear algebra, including vectors, matrices, norms, dot products, linear transformations, eigenvalues, eigenvectors, and more.


---
# 1. Vectors and Vector Operations
---

## 1.1 What is a Vector?
A vector is a quantity that has both magnitude and direction. In computer science, vectors are often represented as lists of numbers. The number of dimensions equals the number of elements in the vector.

For example:
- A 2D vector: $[1, 2]$
- A 3D vector: $[3, 4, 5]$

- **In Data Scince and ML:** It represents single data points or features. Used for distance calculations, embeddings, and feature representation.

In [7]:
import numpy as np

# Define two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("vector a: ", a, "vector dim:", a.shape[0])
print("vector b: ", b, "vector dim:", b.shape[0])

vector a:  [1 2 3] vector dim: 3
vector b:  [4 5 6] vector dim: 3


## 1.2 Vector Basic Operations

- **Vector Scaling**
To scale a vector, multiply each component by a scalar. For example:
$$ 2\cdot [1, 2, 3] = [2 \cdot 1, 2 \cdot 2, 2\cdot 3] = [2, 4, 6]$$

- **Vector Addition**
To add two vectors, add their corresponding components. For example:
$$[1, 2, 3] + [4, 5, 6] = [1 + 4, 2 + 5, 3 + 6] = [5, 7, 9]$$

- **Vector Subtraction**
To subtract two vectors, subtract their corresponding components. For example:
$$[1, 2, 3] + [4, 5, 6] = [1 - 4, 2 - 5, 3 - 6] = [-3, -3, -3]$$


In [5]:
# Vector scaling
scalar = 2
scaled_vector = scalar * a
print("Scaled Vector:", scaled_vector)

# Vector addition
vector_addition = a + b
print("Vector Addition:", vector_addition)

# Vector subtraction
vector_subtraction = a - b
print("Vector Subtraction:", vector_subtraction)

Scaled Vector: [2 4 6]
Vector Addition: [5 7 9]
Vector Subtraction: [-3 -3 -3]


## 1.3 Vector Norms

- **L1 Norm (Manhattan Norm)**: The L1 norm is the sum of the absolute values of the vector components.
- **L2 Norm (Euclidean Norm)**: The L2 norm is the square root of the sum of the squared components of the vector.
- **L∞ Norm (Max Norm)**: The L∞ norm is the maximum absolute value among the components of the vector.


In [9]:
# Calculate L1 norm (Manhattan Norm)
l1_norm = np.linalg.norm(a, ord=1)
print("L1 Norm of vector a:", l1_norm)

# Calculate L2 norm (Euclidean Norm)
l2_norm = np.linalg.norm(a) # default value or ord=2
print("L2 Norm of vector a:", l2_norm)

# Calculate L∞ norm (Max Norm)
linf_norm = np.linalg.norm(a, ord=np.inf)
print("L∞ Norm of vector a:", linf_norm)

L1 Norm of vector a: 6.0
L2 Norm of vector a: 3.7416573867739413
L∞ Norm of vector a: 3.0


## 1.4 Dot Product
The dot product of two vectors measures how much they point in the same direction.


In [10]:
# Calculate dot product
dot_product = np.dot(a, b)
print("Dot Product of a and b:", dot_product)

Dot Product of a and b: 32


---
# 2. Matrices and Matrix Operations
---

### 2.1 What is a Matrix?
A matrix is a two-dimensional array of numbers, organized into rows and columns. In data science, matrices are used to represent:

- **Datasets**: Each row represents a data point, and each column represents a feature.
- **Transformations**: Matrices are used to apply linear transformations (e.g., scaling, rotation) to data.
- **Weights in Machine Learning**: In models like linear regression or neural networks, weights are often represented as matrices.

**Example:**

Suppose you have a dataset of three houses with the same features as above:
$$
\text{Dataset} = \begin{bmatrix}
1500 & 3 & 10 \\
2000 & 4 & 5 \\
1200 & 2 & 20
\end{bmatrix}
$$

**Here:**
- Each row represents a house.
- Each column represents a feature (size, bedrooms, age).

In [16]:
# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("matrix A: \n", A, "\nnumber of vectores:",  A.shape[1],"each vector dim:", A.shape[0])
print("\n\nmatrix B: \n", B, "\nnumber of vectores:",  B.shape[1],"each vector dim:", B.shape[0])

matrix A: 
 [[1 2]
 [3 4]] 
number of vectores: 2 each vector dim: 2


matrix B: 
 [[5 6]
 [7 8]] 
number of vectores: 2 each vector dim: 2


In [15]:
# Matrix addition
matrix_addition = A + B
print("Matrix Addition:\n", matrix_addition)

# Matrix multiplication
matrix_multiplication = np.dot(A, B)
print("Matrix Multiplication:\n", matrix_multiplication)

# Matrix multiplication or but with aother method
matrix_multiplication = A @ B
print("Matrix Multiplication:\n", matrix_multiplication)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


### 2.2 Matrix Rank
The **rank of a matrix** is the maximum number of **linearly independent rows or columns** in the matrix. In other words, it tells you:
- How many rows (or columns) are unique and not just linear combinations of other rows (or columns).
- The dimensionality of the vector space spanned by the rows or columns of the matrix. يعني الفيكتورز  المكون منها الماتركس دي والي تخليني اقدر اعبر عن السبيس كله واي فيكتور جديد هيكون بمعلوميه الفيكتورز الاندبيندت دول 

**What is Matrix Rank in Data Science and ML?**

- In a dataset, the rank of the feature matrix indicates whether there are redundant (linearly dependent) features.
- If the rank is less than the number of features, some features are linear combinations of others, which can lead to multicollinearity in regression models.

**Applications of Matrix Rank in Data Science and ML**

[a] Linear Regression
- In linear regression, the rank of the feature matrix $X$ determines whether the system $X^T X \beta = X^T y$ has a unique solution.
- If $X$ is not full rank, the system is underdetermined, and regularization is needed.

[b] Dimensionality Reduction (PCA)
- PCA uses the rank of the covariance matrix to identify the principal components (directions of maximum variance) in the data.
- The rank determines how many principal components are needed to represent the data effectively.

[c] Collaborative Filtering (Recommendation Systems)
- In recommendation systems, the user-item interaction matrix is often low-rank.
- Matrix factorization techniques (e.g., Singular Value Decomposition) exploit this low-rank structure to predict missing values.

[d] Image Compression
- Images can be represented as matrices, and their rank determines the compressibility.
- Low-rank approximations (e.g., using SVD) are used to compress images by retaining only the most important information.



In [17]:
# Calculate matrix rank
rank = np.linalg.matrix_rank(A)
print("Rank of matrix A:", rank)

Rank of matrix A: 2


In [18]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]